# Generated by Django 3.1.7 on 2021-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=50)),
                ('token_type', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=50)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('show_type', models.CharField(max_length=25)),
            ],
        ),
    ]
