# Generated by Django 3.1.7 on 2021-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20210325_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='access_token',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='refresh_token',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token_type',
            field=models.CharField(max_length=48),
        ),
    ]
