# Generated by Django 3.1.7 on 2021-04-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('languages', models.TextField(default='NULL')),
                ('show_type', models.CharField(choices=[('shows', 'shows'), ('episodes', 'episodes')], max_length=8)),
            ],
        ),
    ]
